baseURL: https://boring-lamarr-ca7b4d.netlify.app
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Hi, my name is Lauren and this is my website showcasing my data anlytics projects! Enjoy!
    title: Lauren Wade
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lwade.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7878924085
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Lauren Wade
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/laurenwade_
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/lauren-wade
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/laurenjwade
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/about
      - name: Projects
        url: projects
      - name: CV
        url: blogs/cv
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic08.jpg
        subtitle: 
        title: About Me
        url: blogs/about
      - image: pic07.jpg
        subtitle: 
        title: My CV
        url: blogs/cv
      - image: pic012.jpg
        subtitle: 
        title: Pre-Program Assignment
        url: blogs/preprogram
      - image: pic11.jpg
        subtitle: 
        title: Climate Change Project
        url: blogs/ipsum
      - image: pic10.jpg
        subtitle: 
        title: Salary Assignment
        url: blogs/salary
      - image: pic13.jpg
        subtitle: 
        title: Contact Me
        url: blogs/contact
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
